### ISSUE TITLE
Event subscription example

### ISSUE THREAD

**Issue by Iwantmorebugs** [justmobilize/particle-app-windows-example#1]
Hello ! 

Thank you for your great work. The example of how to use the SDK is quite interesting.
I wonder if you could drop a small example of how to use the Event subscription functions. I would be really thankful as I am having some trouble with it.

Thank you very much

**Comment by justmobilize** [comment]
@Iwantmorebugs I would recommend looking at the [Windows app](https://github.com/particle-iot/particle-app-windows), it's used in there. I would be happy to update this, but there hasn't been much interest

**Comment by Iwantmorebugs** [comment]
@justmobilize Thank you for the tip ! I've been checking it actually, trying to find a proper example. We are trying to create a centralized-app for our Particle projects that involves the subscription and so on.

**Comment by justmobilize** [comment]
Have you looked at the [particle-windows-sdk](https://github.com/particle-iot/particle-windows-sdk)? Search for `SubscribeToDeviceEventsWithPrefixAsync`

**Comment by justmobilize** [comment]
And then here in the Windows App: https://github.com/particle-iot/particle-app-windows/blob/master/Particle.Tinker.Shared/Pages/Device/EventsPage.cs

**Comment by Iwantmorebugs** [comment]
Oh, that's a great list of examples ! It actually covered most of what I needed. 

Thank you very much !
